language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

matrix:
  include:
    - python: '3.7'  # temp solution until python 3.7 is more cleanly supported
      dist: xenial
      sudo: true
  allow_failures:
    - python: '3.7'  # dependencies are blocking installation
  fast_finish: true

install:
  - pip install .
  - pip install -r requirements-dev.txt
  - pip list
  - pip show choicemodels

script:
  - coverage run --source choicemodels --module pytest --verbose

after_success:
  - coverage report --show-missing
  - coveralls
