name: Installation

# This workflow tests installation from Pip and Conda across a range of Python versions
# and operating systems. You can run this manually after a new release is posted to
# confirm that it installs smoothly. This workflow also runs periodically in the
# background to catch dependency updates that cause problems.

on:
  # push:
  # pull_request:
  workflow_dispatch:
  schedule:
  - cron: '0 3 * * 1'  # every Monday at 3am UTC (Sunday evening Calif time)

jobs:
  build-pip:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # add back macos-latest and windows-latest when issue #70 is resolved
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install ChoiceModels
      run: |
        pip install choicemodels pytest
    - name: Run tests
      run: |
        cd tests
        pytest -s

  build-conda:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}  # needed for conda persistence
    strategy:
      matrix:
        # add back macos-latest and windows-latest when issue #70 is resolved
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install ChoiceModels
      run: |
        conda install choicemodels pytest --channel conda-forge
    - name: Run tests
      run: |
        cd tests
        pytest -s
